# https://www.elastic.co/guide/en/elasticsearch/reference/current/settings.html

# NOTE: can use ${FOO} for env interpolation
# https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-network.html
network.host: 127.0.0.1
http.port: 10042
# cluster.name: "dubo-elastic"
# Disable cluster search
# XXX this is still messy / noisy
discovery.type: "single-node"
