# https://www.elastic.co/guide/en/elasticsearch/reference/current/settings.html

# NOTE: can use ${FOO} for env interpolation
# https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-network.html
network.host: 127.0.0.1
http.port: 10042
# cluster.name: "dubo-elastic"
# Disable cluster search
# XXX this is still messy / noisy
discovery.type: "single-node"

# Giving up on elastic "security" for now
#xpack:
#  security:
#    enabled: true

# Prevent swapping - also check docker --memory-swap
# bootstrap.memory_lock: true

#xpack:
    #transport:
      #ssl:
        #enabled: true
        #supported_protocols: "TLSv1.2"


#authc:
  #password_hashing:
    #algorithm: "pbkdf2"


    #fips_mode:
      #enabled: true

